#!name=WeChatNoAD
#!desc=WeChatNoAD
#!author=WeChatNoAD

#WeChatNoAD by Choler&NobyDa

[URL Rewrite]
#^https?:\/\/mp\.weixin\.qq\.com\/mp\/cps_product_info\?action reject-dict
#^https?:\/\/mp\.weixin\.qq\.com\/mp\/cps_product_info reject
^https:\/\/mp\.weixin\.qq\.com\/mp\/(cps_product_info|getappmsgad|masonryfeed|relatedarticle)\? reject-dict

[Script]
WeChatNoAD=type=http-response,pattern=^https?:\/\/mp\.weixin\.qq\.com\/mp\/getappmsgad,requires-body=1,script-path=https://raw.githubusercontent.com/EXPUN/s/master/rules/wechatnoad.js

[MITM]
hostname = %APPEND% mp.weixin.qq.com
